title: Squiggly Lines
email: dre.west@outlook.com
description: >-
  Programming, Development, Language and some other interests
baseurl: ""
url: "https://dotrar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: DWestcook
github_username:  Dotrar
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-feed
  - jekyll-remote-theme
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
